output "system_users" {
  description = "System users generated by the core module."
  sensitive   = true
  value       = module.systems.users
}

output "application_users" {
  description = "Manually selected applilcation users generated by each application_database module."
  sensitive   = true
  value = {
    raw = module.raw_db.user
  }
}
